### ISSUE TITLE
Revert #301 once aiohttp timer handle churn is reduced

### ISSUE THREAD

**Issue by bdraco** [home-assistant-libs/aioshelly#610]
Once https://github.com/aio-libs/aiohttp/pull/8608 merges we can remove the custom ping/pong implementation as the issue will be solved upstream

```[tasklist]
### Tasks
- [x] Wait for aiohttp 3.10.2 release
- [x] Wait for aiohttp to be bumped to 3.10.2
- [x] Rework a revert PR for #301
```
